require:
  - solidus_dev_support/rubocop

inherit_from: .rubocop_todo.yml

FactoryBot/CreateList:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false

FactoryBot/FactoryNameStyle:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

FactoryBot/FactoryClassName:
  Enabled: false

FactoryBot/RedundantFactoryOption:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2
